In [4]:
import pandas 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd 

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
#Similitud con factor (1): Status de la relación sentimental
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_1 = "miedo de denunciar al activo, nunca lo denunció por miedo,  refirió sentirse temorosa , podía buscarla y cumplir su amenaza de matarla, que ella no quería estar cerca de ese lugar, temor a que él pudiera encontrarla y ocasionarle un daño mayor, Trató de no mostrarle miedo ni que le estaba afectando porque si lo hacía la mataría, Tuvo miedo por la vida de su mamá, Regresaba con él, ya que le refería que le temía debido a que era una persona muy violenta, además de que la amedrentaba diciéndole que si lo dejaba, iba a atentar contra su familia, Le refirió que no se regresaba porque tenía miedo, La referida tenía miedo al agresor y a la violencia ejercida por este, pues dicho miedo inhibe y aleja a las afectadas, Los malos tratos hacía su hija nunca los denunció porque no la dejaba salir, que era muy celoso, que le decía qué necesidad tenía de andar en la calle, Al observar al acusado solicitó que no se advirtiera en la cámara porque le tenía miedo,Tenía miedo de contar lo sucedido por temor al acusado, reacción con temor al agresor, tuvo miedo hacia el denunciado, tenía miedo de que la matará o le hiciera algo a su hermano, ser el padre con apellidos, porque era la madre de sus hijos y su exesposa, por lo que su menor hijo empezó a llorar, Quien es hija de la víctima, No tenían hijos en común, Violencia familiar,  Sus hijos escuchaban normalmente las discusiones que tenían, Había agresiones físicas y verbales por parte de su padre a su mamá en otras ocasiones, La violencia reiterada que el menor vive, La menor se encontraba bajo violencia familiar.  La existencia de un ambiente de violencia familiar reiterada,  madre e hija se encontraban inmersas en un contexto de violencia y negligencia por parte del acusado."
    
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_1
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.68605871]]
[[1.         0.71140609]]
[[1.         0.70062788]]
[[1.         0.70868437]]
[[1.         0.69447634]]
[[1.        0.7500537]]
[[1.         0.74853462]]
[[1.         0.70323742]]
[[1.         0.67330884]]
[[1.         0.66287926]]
[[1.        0.6787097]]
[[1.         0.72138634]]
[[1.         0.71788437]]
[[1.         0.70867425]]
[[1.         0.68482567]]
[[1.         0.68658107]]
[[1.         0.71737204]]
[[1.         0.72555524]]
[[1.         0.68076142]]
[[1.        0.7415507]]
[[1.         0.67796174]]
[[1.        0.7500537]]
[[1.         0.70868437]]
[[1.         0.70745521]]
[[1.         0.73212237]]
[[1.         0.68097424]]
[[1.         0.65386704]]
[[1.         0.72311252]]
[[1.        0.6991547]]
[[1.         0.75003385]]
[[1.         0.69069817]]
[[1.         0.61125802]]
[[1.         0.66654394]]
[[1.         0.71510123]]
[[1.         0.74443978]]
[[1.         0.68621469]]
[[1.         0.68840154]]
[[1.       0.717839]]
[[1.        0.7334292]]
[[

In [10]:
#Similitud con factor (2): Economía familiar
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_2 = "superioridad material, hubo violencia económica porque no le brinda dinero y no la dejaba trabajar."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_2
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.10526424]]
[[1.         0.11315391]]
[[1.         0.11357303]]
[[1.         0.11419572]]
[[1.         0.10510647]]
[[1.         0.11843067]]
[[1.         0.11453449]]
[[1.         0.10147636]]
[[1.         0.12478478]]
[[1.         0.08425277]]
[[1.         0.09385474]]
[[1.         0.10990804]]
[[1.         0.11928015]]
[[1.         0.10881564]]
[[1.         0.10335598]]
[[1.         0.11825202]]
[[1.         0.11975104]]
[[1.         0.08631886]]
[[1.         0.08983853]]
[[1.         0.11900242]]
[[1.        0.1138604]]
[[1.         0.11843067]]
[[1.         0.11419572]]
[[1.         0.09770381]]
[[1.         0.10222028]]
[[1.         0.12232615]]
[[1.         0.08911267]]
[[1.         0.10291345]]
[[1.         0.07356916]]
[[1.         0.13134962]]
[[1.         0.11749112]]
[[1.         0.08008964]]
[[1.         0.09569355]]
[[1.         0.11728351]]
[[1.         0.12398624]]
[[1.         0.11734667]]
[[1.         0.08644969]]
[[1.         0.10099405]]
[[1.         0

In [11]:
#Similitud con factor (3): Entorno social
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_3 = "tendencia a minimizar las situaciones de riesgo en las que se encontraba, es decir se encontraba en una incapacidad para sustraerse ante las situaciones de riesgo, Ella lo quería justificar, No tener temor al denunciado ya que todo se le resbalaba, ella ya normaliza esa violencia."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_3
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.39855411]]
[[1.         0.35919594]]
[[1.         0.35445791]]
[[1.         0.37078594]]
[[1.         0.37193018]]
[[1.         0.38763336]]
[[1.         0.37325543]]
[[1.         0.34549301]]
[[1.         0.33722852]]
[[1.         0.36209529]]
[[1.         0.35880125]]
[[1.         0.38111208]]
[[1.         0.38289157]]
[[1.         0.35610087]]
[[1.         0.36479554]]
[[1.         0.33670429]]
[[1.         0.40411642]]
[[1.        0.3569401]]
[[1.         0.36331308]]
[[1.         0.36124687]]
[[1.         0.33256589]]
[[1.         0.38763336]]
[[1.         0.37078594]]
[[1.         0.39600285]]
[[1.         0.35337073]]
[[1.         0.34773866]]
[[1.         0.33998156]]
[[1.         0.33492931]]
[[1.         0.41808587]]
[[1.         0.35119354]]
[[1.         0.34472283]]
[[1.         0.30572677]]
[[1.         0.34893383]]
[[1.         0.36346632]]
[[1.         0.38365958]]
[[1.         0.35348293]]
[[1.        0.3823171]]
[[1.        0.3763709]]
[[1.         0.371

In [6]:
#Similitud con factor (4): Consumo de sustancias nocivas 
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_4 = "Ambos son drogadictos y en ese momento se encontraban intoxicados. Le exigía que le diera dinero para comprar drogas.Consumo de sustancias psicoactivas por parte de éste. El agresor consume drogas.Aunado al consumo de droga como cristal."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_4
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.        0.3640134]]
[[1.         0.34983453]]
[[1.         0.35176588]]
[[1.         0.34623872]]
[[1.         0.35827707]]
[[1.         0.35695592]]
[[1.        0.3642919]]
[[1.         0.34070991]]
[[1.         0.33119848]]
[[1.         0.38067404]]
[[1.         0.36668921]]
[[1.         0.36072751]]
[[1.         0.37100288]]
[[1.         0.34201626]]
[[1.         0.38405938]]
[[1.         0.33292745]]
[[1.        0.3621075]]
[[1.        0.3583251]]
[[1.         0.35937709]]
[[1.         0.35974648]]
[[1.        0.3313976]]
[[1.         0.35695592]]
[[1.         0.34623872]]
[[1.         0.37198941]]
[[1.         0.34884127]]
[[1.         0.34419912]]
[[1.         0.34484268]]
[[1.        0.3874776]]
[[1.         0.40327603]]
[[1.         0.33997486]]
[[1.         0.33408027]]
[[1.         0.34626463]]
[[1.        0.3470192]]
[[1.         0.36428438]]
[[1.         0.35059647]]
[[1.         0.34516627]]
[[1.         0.36941059]]
[[1.         0.35085389]]
[[1.         0.34439758]]


In [15]:
#Similitud con factor (5): Protección a la víctima
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_5 = "Siendo ayudada por un tercero, Pidió ayuda a una vecina Ella le mencionaba que le pedía ayuda que porque el muchacho le andaba pegando. Los vecinos le decían que porqué lo aguantaba y que ella les decía que porque lo quería mucho, que no podía vivir sin estar con él, Entró la hija, Entró la vecina. Entre ambas lo quitaron de encima de la víctima, La intervención de la hija de la víctima y su vecina quienes impidieron que el acusado consumara su actuar.          Su hija fue la que habló al 911 para pedir apoyo, Ella fue con su vecina para pedirle ayuda, Abuelita trató de calmar al padre y que éste intentó pegarle con un exprimidor de limones, Bisabuela, Personas cercanas quien le brindaba apoyo, La menor no contaba con redes de apoyo eficaces, pues su familia era conocedora de los maltratos que sufría y no obstante a ello no lo denunciaban, La abuela bisabuela y una vecina, Llegó en ese momento la mamá, Le gritó a su suegra pidiendole ayuda."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_5
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.62008418]]
[[1.         0.62401376]]
[[1.         0.61281077]]
[[1.         0.61517016]]
[[1.         0.63748078]]
[[1.         0.64614336]]
[[1.         0.64964145]]
[[1.         0.63357689]]
[[1.       0.598285]]
[[1.         0.59580702]]
[[1.         0.61139802]]
[[1.         0.67543877]]
[[1.         0.63722255]]
[[1.         0.63930873]]
[[1.         0.60972508]]
[[1.         0.61620125]]
[[1.         0.64863155]]
[[1.       0.623517]]
[[1.         0.61059944]]
[[1.         0.63335986]]
[[1.         0.61541816]]
[[1.         0.64614336]]
[[1.         0.61517016]]
[[1.        0.5969245]]
[[1.        0.6355738]]
[[1.         0.60582957]]
[[1.         0.59505083]]
[[1.         0.64974977]]
[[1.         0.58975166]]
[[1.         0.67780441]]
[[1.         0.61962957]]
[[1.         0.53643269]]
[[1.      0.62678]]
[[1.         0.64619417]]
[[1.        0.6368289]]
[[1.         0.63453079]]
[[1.        0.6159078]]
[[1.         0.62397533]]
[[1.         0.62103011]]
[[1.    

In [18]:
#Similitud con factor (6): Manifestación de violencia
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_6 = "Había sido objeto de jalones y gritos, había amenazado con un arma de fuego, no quería seguir con el activo por las múltiples agresiones que sufría antecedentes de violencia contra la víctima, violencia física sufrida por la víctima e inclusive habían visto golpeada que había discutido porque su pareja le había prestado un dinero, Violencia familiar, Él le mencionó que la iba a matar, La existencia de antecedentes o datos relativos a violencia ejercida por el sujeto activo en contra de la víctima; conducta que no llegó a producirse por causas ajenas a la voluntad de quien representó el hecho, Amenazas, Ella no pudo dormir esa noche, Antecedentes de amenazas de muerte, antecedentes que antes de que esto pasara su papá ya había hecho mención de agredir o amenazar de muerte a su mamá, El sujeto le decía constantemente que la iba a matar y que la iba a matar, Ya ha habido antecedentes de amenazas con cuchillos, Ya había puesto varias denuncias por agresiones físicas como cachetadas, puñetazos, la había tratado de ahorcar y amenazas de muerte, Todas las expresiones verbales y agresiones físicas, eran dirigidos a que se le iba a suprimir de la vida, Destaca que este la violentaba constantemente, Antecedentes de violencia a los que era expuesta la menor occisa, Ahí mismo presentaba síndrome de niño maltratado, Constantemente las agredía física y verbalmente y no les suministraba los cuidados y alimentos necesarios, Ha robado, golpeado a policías y a renteros, superioridad física o material, la mantenía a la fuerza en su relación, el activo tenía a su hija a la fuerza, si le hablas a la policia vamos a ver a quién le creen más desproporción de fuerza es más lo voy a ir a matar y si tú también te metes también la vas a llevar, El activo ejercía ese poder hacia la víctima, Control del victimario hacia la víctima, El acusado quien tenía una autoridad sobre ellas al no permitirles salir libremente ni comunicarse con sus familiares,  era muy agresivo, enterados de sus conductas agresivas con anterioridad a los hechos, El imputado le decía que la iba a matar, la comenzó a ahorcar con ambas manos gritándole “te voy a matar”, golpeando también a su menor hijo en tres ocasiones comenzando a golpear en la cara, brazos, cabeza, pecho y espalda, al ver a su concumbina la agredió verbalmente, el acusado tenía del cuello a la víctima , aliteración emocional, Eventos traumáticos en donde estuvo en riesgo la integridad física de la víctima, Ella se encuentra en la fase de golpes en el ciclo de violencia, Estaba muy enojado, Él le comenzó a reclamar, luego la empujó y le dio puñetazos en el cuerpo y en la cara, ella cayó al suelo y la comenzó a patear en el cuerpo, en la cabeza y en los brazos, Cabezazo, Realizó actos de ejecución idóneos encaminados directamente a la privación de la vida. Delira que lo persiguen que lo están siguiendo y que esto conlleva agresiones tanto físicas como verbales a la madre, a la víctima y a su hermano Su padre le ha hecho agresiones verbales diciéndole pendeja que no sirve para nada, devaluándola, humillándola y agresiones físicas, golpes en el rostro, en el estómago, patadas, Las lesiones que sufrió y acciones ejecutadas en su contra en su conjunto a juicio del suscrito juzgador pudieron ocasionarle la  muerte, Él la empezó a insultar con palabras fuertes, Propinarle golpes contusos en cuerpo y abdomen, La menor y su menor hija habitaban con el ahora acusado, que clientes que llegaban a su negocio le comentaban que su nieta sufría mucho, ya que la golpeaba, humillaba en la calle, e inclusive no le daba de comer, el denunciado la insultaba, el denunciado le refería conductas chantajistas, le empezó a realizar cortadas en el cuello, Le pegó con el puño cerrado en el labio, Dándole cachetada, La agarró del cuello a la víctima, El acusado insultaba a su pareja, diciéndole que era una puta, Ella en su infancia llegó a sufrir agresión sexual por parte de su padre sin embargo no denunció considerando que era una víctima de corta edad."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_6
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.79841009]]
[[1.         0.83219218]]
[[1.         0.80958233]]
[[1.         0.79485521]]
[[1.         0.79959769]]
[[1.         0.83571135]]
[[1.        0.8356062]]
[[1.         0.81964915]]
[[1.         0.80440711]]
[[1.         0.77985489]]
[[1.         0.79627685]]
[[1.         0.82284787]]
[[1.         0.80294113]]
[[1.        0.8175672]]
[[1.         0.78549009]]
[[1.         0.81387492]]
[[1.         0.82451779]]
[[1.       0.799563]]
[[1.        0.7889923]]
[[1.         0.83067012]]
[[1.         0.82001776]]
[[1.         0.83571135]]
[[1.         0.79485521]]
[[1.         0.76715232]]
[[1.         0.81719884]]
[[1.         0.79696891]]
[[1.         0.76282203]]
[[1.         0.80946541]]
[[1.         0.76515026]]
[[1.         0.84061641]]
[[1.         0.79635052]]
[[1.        0.7194637]]
[[1.         0.79179945]]
[[1.         0.83751927]]
[[1.         0.83715166]]
[[1.         0.80558756]]
[[1.        0.7796842]]
[[1.         0.80620803]]
[[1.         0.82665589]]


In [19]:
#Similitud con factor (7): Disfunciones cerebrales
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_7 = "Afecto de ansiedad tristeza y temor, Daño psico - emocional, Baja autoestima de la víctima, Ella cuenta con baja autoestima. Alteración emocional, Presentaba daño psicológico, La evaluada presentaba un daño físico psicológico,Daño psico emocional."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_7
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.22574108]]
[[1.         0.23038442]]
[[1.         0.22045872]]
[[1.        0.2312215]]
[[1.         0.23534233]]
[[1.         0.22508447]]
[[1.         0.23343767]]
[[1.         0.22175191]]
[[1.         0.23720853]]
[[1.         0.21442295]]
[[1.         0.20652332]]
[[1.        0.2109707]]
[[1.         0.23126674]]
[[1.         0.20803134]]
[[1.         0.20837226]]
[[1.         0.23273504]]
[[1.         0.22402397]]
[[1.         0.16478391]]
[[1.        0.1895075]]
[[1.         0.21797701]]
[[1.         0.24065649]]
[[1.         0.22508447]]
[[1.        0.2312215]]
[[1.         0.22468934]]
[[1.         0.21530642]]
[[1.         0.21657776]]
[[1.        0.2188478]]
[[1.         0.22582613]]
[[1.         0.20095988]]
[[1.         0.23842299]]
[[1.         0.19810409]]
[[1.         0.20005366]]
[[1.         0.20283135]]
[[1.        0.2227369]]
[[1.         0.23155601]]
[[1.         0.23304343]]
[[1.         0.19936572]]
[[1.         0.22231399]]
[[1.         0.24268014]

In [20]:
#Similitud con factor (8): Eficiencia institucional
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_8 = "Pidiendo ayuda a la policía causando por su actuar daños en la integridad psico emocional tanto de la Ciudadana, ella le habló a la policía llegando elementos que lo detienen."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_8
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.42612393]]
[[1.         0.47142857]]
[[1.         0.41821215]]
[[1.         0.42821189]]
[[1.         0.42977586]]
[[1.        0.4782951]]
[[1.         0.45568022]]
[[1.         0.44933653]]
[[1.         0.44718968]]
[[1.         0.40216325]]
[[1.         0.44072617]]
[[1.        0.4562664]]
[[1.         0.45649564]]
[[1.         0.45132072]]
[[1.         0.41438463]]
[[1.         0.44936996]]
[[1.         0.46194539]]
[[1.         0.41594661]]
[[1.         0.41080175]]
[[1.         0.45341398]]
[[1.         0.46291993]]
[[1.        0.4782951]]
[[1.         0.42821189]]
[[1.         0.41390607]]
[[1.         0.44260257]]
[[1.         0.43452267]]
[[1.         0.38298362]]
[[1.         0.44090176]]
[[1.         0.38738962]]
[[1.         0.47530457]]
[[1.         0.44019588]]
[[1.         0.36790536]]
[[1.         0.41311652]]
[[1.         0.46446857]]
[[1.         0.45050558]]
[[1.         0.44317437]]
[[1.         0.40553688]]
[[1.         0.43558803]]
[[1.         0.440

In [21]:
#Similitud con factor (9): Acceso y uso de armas 
x=0
while x <=257:
    sentencias = pandas.read_csv('/Users/andreasb/Desktop/TEC/Concentración/Actividades/procesar_textos/sentencias_completas.csv')
    sentencias1 = sentencias.iloc[x,1]
    ejemplo = str(sentencias1)
    factor_9 = "detonaciones de arma de fuego, siempre portaba arma de fuego, impactos de arma de fuego, proyectil de arma de fuego, objeto punzocortante, lesiones originadas por un instrumento punzocortante, portaba consigo una navaja, un arma blanca punzocortante que portaba en contra de la víctima dijo que traía un cuchillo, el acusado le enseñaba un cuchillo que traía en la cintura, le consiguiera una pistola porque iba a matar al papá de la víctima, Estrellar la piedra, Aventar un cenicero, Había sido atacada por él con un cuchillo, Un cuchillo con mango café y la hoja plateada con “dientitos” de aproximadamente entre 20 y 15 centímetros, era hoja se sierra, Punzocortante, un cuchillo o una navaja, Martillo, Le puso un cuchillo del lado derecho en el cuello, Tenía un cuchillo, La estaba ahogando, La estaba asfixiando, Objetos contundentes, como puños, patadas,bates, block, sillas, Block, Objeto punzocortante."
    count_vect = CountVectorizer()
    Document1 = ejemplo
    Document2=factor_9
    
    corpus = [Document1,Document2]
    X_train_counts = count_vect.fit_transform(corpus)
    pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 1','Document 2'])
    
    vectorizer = TfidfVectorizer()
    trsfm=vectorizer.fit_transform(corpus)
    pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 1','Document 2'])
    
    similaridad=cosine_similarity(trsfm[0:1], trsfm)
    print(similaridad)
    x=x+1

[[1.         0.48971824]]
[[1.         0.52476463]]
[[1.         0.49800681]]
[[1.         0.52462428]]
[[1.         0.53205838]]
[[1.         0.49728685]]
[[1.         0.52865531]]
[[1.         0.49049845]]
[[1.         0.49818313]]
[[1.         0.56134577]]
[[1.         0.52587265]]
[[1.         0.52800069]]
[[1.         0.53466283]]
[[1.        0.4889317]]
[[1.         0.52062438]]
[[1.         0.49928912]]
[[1.         0.52692112]]
[[1.         0.52878613]]
[[1.         0.52798491]]
[[1.         0.53851027]]
[[1.         0.49655967]]
[[1.         0.49728685]]
[[1.         0.52462428]]
[[1.         0.51941638]]
[[1.        0.4915293]]
[[1.         0.50531701]]
[[1.         0.49893803]]
[[1.         0.54333706]]
[[1.         0.52730905]]
[[1.         0.56601118]]
[[1.        0.4973023]]
[[1.         0.49494178]]
[[1.         0.52009174]]
[[1.        0.5078699]]
[[1.         0.48972535]]
[[1.         0.50093012]]
[[1.        0.5133516]]
[[1.         0.50322851]]
[[1.        0.5441987]